# Generated by Django 4.2.29 on 2026-05-11 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('assessment_type', models.CharField(choices=[('phq9', 'PHQ-9'), ('gad7', 'GAD-7'), ('pss10', 'PSS-10'), ('full_scan', 'Full wellness scan')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('phq9_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(27)])),
                ('gad7_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('pss10_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('submitted_via', models.CharField(blank=True, default='web', max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('distressed', 'Distressed')], db_index=True, max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('trend_signal', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('model_name', models.CharField(default='random_forest', max_length=80)),
                ('model_version', models.CharField(blank=True, default='', max_length=40)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('breathing', 'Breathing'), ('sleep', 'Sleep'), ('study_balance', 'Study balance'), ('social_support', 'Social support'), ('professional_support', 'Professional support'), ('general_wellness', 'General wellness')], db_index=True, default='general_wellness', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('priority', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='assessments.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'priority'], name='assessments_user_id_cc2e8c_idx'), models.Index(fields=['prediction', 'priority'], name='assessments_predict_bb9e72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', '-created_at'], name='assessments_user_id_162587_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', 'category'], name='assessments_user_id_73386b_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', 'trend_signal'], name='assessments_user_id_9c8825_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', '-completed_at'], name='assessments_user_id_a559c3_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['user', 'assessment_type', '-created_at'], name='assessments_user_id_0f1bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', '-created_at'], name='assessments_status_be3ff1_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(check=models.Q(('phq9_score__isnull', True), models.Q(('phq9_score__gte', 0), ('phq9_score__lte', 27)), _connector='OR'), name='assessment_phq9_score_range'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(check=models.Q(('gad7_score__isnull', True), models.Q(('gad7_score__gte', 0), ('gad7_score__lte', 21)), _connector='OR'), name='assessment_gad7_score_range'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(check=models.Q(('pss10_score__isnull', True), models.Q(('pss10_score__gte', 0), ('pss10_score__lte', 40)), _connector='OR'), name='assessment_pss10_score_range'),
        ),
    ]
