# Generated by Django 4.2.29 on 2026-05-11 14:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('mood_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_label', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('daily_check_in', 'Daily check-in'), ('journal', 'Journal'), ('manual', 'Manual')], db_index=True, default='daily_check_in', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-log_date'], name='moods_moodl_user_id_094d65_idx'), models.Index(fields=['user', 'source', '-log_date'], name='moods_moodl_user_id_5914b3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='moodlog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='unique_mood_log_per_user_day'),
        ),
    ]
