# Generated by Django 4.2.29 on 2026-05-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chats', '0002_chatmessage_message_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['message_index', 'created_at']},
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ai_chats_ch_convers_0ac01a_idx',
            old_name='ai_chats_ch_convers_a3ad49_idx',
        ),
    ]
